### ISSUE TITLE
state file fails to parse

### ISSUE THREAD

**Issue by rscheuermann** [anelendata/handoff#70]
I've noticed that on a regular basis, when running within Fargate, the `state` file is often being appended to instead of replaced. The next run results in a JSON parse error of the state.

My tap is writing the state out periodically. So I end up with multiple lines in the `state` file.

```
{"bookmarks": {"logs": {"last_log_id": 90020201119132953640000367990609114315858551700132462674}}}
{"bookmarks": {"logs": {"last_log_id": 90020201119183036400004102075853902584458116969206382642}}}
{"bookmarks": {"logs": {"last_log_id": 90020201120010908240000567013047630009677054122624286786}}}
{"bookmarks": {"logs": {"last_log_id": 90020201120115037640000487081423750260793218584505483346}}}
{"bookmarks": {"logs": {"last_log_id": 90020201120181441955000644655127442017960359807173001314}}}
{"bookmarks": {"logs": {"last_log_id": 90020201120223154955000655974406276541860470496157499490}}}
```

The [Singer docs](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-singer-with-python) recommend that you save the last line of the file to `state`.

```
tail -1 state.json > state.json.tmp && mv state.json.tmp state.json
```

**Comment by daigotanaka** [comment]
Hi @rscheuermann,

Sorry for not responding to this earlier...since the release of v0.2 and working with an early adopter user and I decided to do a major overhaul and improvement that resulted in handoff v0.3.0. Just released on PyPi (pip install -U handoff).

Thank you for the suggestion on the last line. I believe v0.3 can handle this by adding tail command as the last command to run.

There are a few ways to learn about v0.3:
1. New tutorial on web: https://dev.handoff.cloud/en/latest/tutorial.html
2. Command line tutorial: `handoff quick_start make`
3. handoff recipe (examples): https://github.com/anelendata/handoff_recipe

The second one (command line tutorial) has an issue running in Mac OS...due to the different date command signature. So for now, please refer to 1 and 3.

I hope you will agree that v0.3 offers a better user experience and more powerful features.

Let me know if v0.3 solves the problem. Please feel free to email at daigo@anelen.co (.co not .com) if you need any help.

Thanks for trying out handoff!

Daigo
