### ISSUE TITLE
If a record doesn't match the schema it should stop the streams and kill the task.

### ISSUE THREAD

**Issue by HerbiePorter** [anelendata/handoff#71]
We've observed an issue a few times when we've run a Handoff Task with an out of date schema the Target will throw an error but the Fargate Task will just hang.   This can be replicated by the including a JSON schema in the catalog which doesn't match the records being produced.  The Target throws an error, which appears in the logs, but the Fargate Task doesn't stop, it just hangs and the streams stops processing. 

We've observed this with both the Postgres and Snowflake Targets.

**Comment by daigotanaka** [comment]
Hi @HerbiePorter,

Sorry for not responding to this earlier...since the release of v0.2 and working with an early adopter user and I decided to do a major overhaul and improvement that resulted in handoff v0.3.0. Just released on PyPi (pip install -U handoff).

I would like to see if the problem persists in v0.3.0. It would be great if you can try v0.3.0 out.

There are a few ways to learn about v0.3:
1. New tutorial on web: https://dev.handoff.cloud/en/latest/tutorial.html
2. Command line tutorial: `handoff quick_start make`
3. handoff recipe (examples): https://github.com/anelendata/handoff_recipe

The second one (command line tutorial) has an issue running in Mac OS...due to the different date command signature. So for now, please refer to 1 and 3.

I hope you will agree that v0.3 offers a better user experience and more powerful features.

Let me know if v0.3 solves the problem. Please feel free to email me at daigo@anelen.co (.co not .com) if you need any help.

Thanks for trying out handoff!

Daigo
